### ISSUE TITLE
Fill in the blank isn't saved in browser

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#1]
If I enter something in a "Fill in the blank" question, close the browser, and then visit the quiz again, then this is not restored. The other questions are.

**Comment by iainbryson** [comment]
There are several options in the design of this.  Right now answers are saved on change of focus.  That could be modified to be:

1. Change is saved on return
2. Changes are saved with every character (expensive)
3. Changes are saved every n seconds while the input has focus

I'd advocate for 1 or 3.

Further, an additional option for this would be to revisit the idea of a visual cue to saved or not, so folks aren't surprised.  i.e. unsaved changed cause a red border, saved a green border.

Let me know what you'd like to do here.

**Comment by dtu-compute** [comment]
Would it be possible to save Fill in the blank and free_text on the first mouse click after the form was active?

Or would it be possible to watch the forms (client side) and when no changes have been made for n seconds it sends the form content to the server?

**Comment by iainbryson** [comment]
The first click outside of the text area in both cases *should* trigger save now.  I can't reproduce the issue otherwise.  I'll keep trying, but if you can provide any hints that would be a great help.

Yes, saving on a timer would definitely be possible.  Its a variation of #3 above.  Would you like me to implement that?

**Comment by dtu-compute** [comment]
Excellent =)

Yes, please implement that when you have time and fits in =)
