### ISSUE TITLE
View Hand in doesn't work

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#101]
2016-04-20 3df6236

When entering

H190860
kschstu

it gives a red "success" and not showing the hand in.

Might be related to #69 ?

**Comment by iainbryson** [comment]
Should be fixed by:

commit e4a96071d5dd6380fc0c72590cede3b3d06f170c
Author: Iain Bryson <iain@iain-bryson.ca>
Date:   Thu Apr 21 16:12:03 2016 +0200

    Make “View Hand In” not require a quiz.  Fixes #100
