### ISSUE TITLE
Question options order not static in results

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#102]
When clicking Results as a student the order of the question options gets randomized compared to then the quiz was taken.

**Comment by iainbryson** [comment]
Martin, I'm having some trouble reproducing this. The particular instance that a student answers and hands in should have an array of questions and there's nothing to mutate that array.

Of course, it's going to be a different order for random sections between "View as Student" or "View as Teacher" and any individual student's hand in.

I'll need to figure out a way of adding logging to catch this...

**Comment by dtu-compute** [comment]
Let me see if I can him to reproduce it.

**Comment by iainbryson** [comment]
*ping* reminder to try and reproduce if possible

**Comment by dtu-compute** [comment]
Please see the email I just sent "Fwd: Re: Question options order not static in results"
