### ISSUE TITLE
All that apply selects an extra row

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#105]
2016-04-20 3df6236

If you clone Q1469 and in the second all that apply select the first to, when when clicking Hand in, it have also selected the third. In Results is it shown correct.

He suspect this bug is trickered when fill in the blank are also in the quiz.

**Comment by iainbryson** [comment]
There is a bug I found here, but It's not exactly the same description

It looks like if you _ever_ select an option for all that apply, it says selected when handing in. 

Unlike this report however, when I select the options, it looks like everything is functioning fine.
