### ISSUE TITLE
Latex isn't always rendered

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#112]
This issue were also in the previous build.

In View as Student it always work.

![222](https://cloud.githubusercontent.com/assets/13518486/14812416/78863dc4-0b9d-11e6-8e62-557dd7c0be61.png)

**Comment by iainbryson** [comment]
Is there a quiz which always reproduces this?  If it's random, I'm concerned it's some kind of race condition.  If so, getting the client console log to show this would be beneficial: the server knows nothing about this.

**Comment by dtu-compute** [comment]
I asked him yo reproduce it this morning, and he says it might have been his own fault, so we should just close it.
