### ISSUE TITLE
Unanswered questions should count as wrong

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#115]
In Q1485 and Q1486 are there no questions that need review. The feedback level is 1.

If the student doesn't answer any of the questions, the he gets "Questions remain to be graded" which should have been all wrong.

**Comment by iainbryson** [comment]
To be precise: do you mean that even a manually-graded answer counts as wrong if it’s blank?  In that case, we can automatically grade certain manually-graded questions?

Of course, it’s a clear bug if _automtically_-graded questions are not counted wrong.  Is that happening too?

**Comment by dtu-compute** [comment]
> To be precise: do you mean that even a manually-graded answer counts as wrong if it’s blank? In that case, we can automatically grade certain manually-graded questions?

We better let a human do that, even though it result is clear.

> Of course, it’s a clear bug if _automtically_-graded questions are not counted wrong. Is that happening too?

Yes, that is the issue and that feedback message is for questions that needs review.
