### ISSUE TITLE
Max time is missing

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#120]
See screenshots.

![a1](https://cloud.githubusercontent.com/assets/13518486/14955480/82087c5e-107a-11e6-9284-496ef2fa588a.png)

![a2](https://cloud.githubusercontent.com/assets/13518486/14955481/8622231c-107a-11e6-85c4-0cebcac7e3b7.png)

**Comment by iainbryson** [comment]
Do you know which is the one set by the professor?  Just to double check this.

**Comment by dtu-compute** [comment]
You mean if he can remember what he used as max time?

**Comment by iainbryson** [comment]
Yes. Whether it was unlimited or a fixed value (and what that value was). I don't see in the code how the value could be empty; if it's nil, there should be the infinity symbol and if it's a value, it should be a number. So it's confusing from the code how this could happen...

**Comment by dtu-compute** [comment]
I have just tried on Chrome and Firefox on Windows, as it works there. My thought was it was a missing font issue. Also works fine on my Linux.

Next time I see him, I will take a look in the Firefox console if there are any errors there.

**Comment by iainbryson** [comment]
I think I figured it out.  The issue would reproduce if the max_time is < 1 hour.  Is that what he was doing?

**Comment by dtu-compute** [comment]
I think he used 15 minutes for many of his recent tests.

Very nice debugged =)
