### ISSUE TITLE
Wrong start and end times

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#121]
The start and end time when taking a quiz are not the once that the quiz maker have written.

Also the time format is not the same as in Edit Meta and grid view.

Notice on the last screenshot that it says 18:05, where the dimmed end time says 18:10.

![a1](https://cloud.githubusercontent.com/assets/13518486/14955527/df00c3a8-107a-11e6-85fc-5c153664311c.png)

![a3](https://cloud.githubusercontent.com/assets/13518486/14955546/f606994c-107a-11e6-91db-a664e44fad66.png)

![a5](https://cloud.githubusercontent.com/assets/13518486/14955590/40b81b82-107b-11e6-9b7a-e3024de05e6b.png)

**Comment by iainbryson** [comment]
There are two separate issues here:

(1) The start and end times were not always being translated to the right timezone in the views. 
(2) End times for quizzes with non-nil max_times were taken to be the time the user starts the quiz + max time— i.e., the end time for the particular hand-in and not the quiz itself.
