### ISSUE TITLE
Attempts becomes quizzes

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#122]
It seams like each time you take a quiz, a copy of the quiz is added to the list.

Notice that the end time is different eventhough that it is the same quiz. Looking at the second screenshot you can see, that it is not even the hand in times that is written in the end time. So the end times are very weird.

![b1](https://cloud.githubusercontent.com/assets/13518486/14957349/2dd8298a-1085-11e6-9b24-449423e46575.png)

![b2](https://cloud.githubusercontent.com/assets/13518486/14957353/3280cef6-1085-11e6-94c4-2d5dd568dae0.png)

![a6](https://cloud.githubusercontent.com/assets/13518486/14956375/b5291d6e-107f-11e6-884d-2f964a6196d5.png)

**Comment by iainbryson** [comment]
This seems to be fixed right now
