### ISSUE TITLE
Admin and student mix

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#123]
Notice a mix of student and admin.

He think he logged in as student in one tab and then in another tab logged in as admin, and then reloaded the student tab.

![a8](https://cloud.githubusercontent.com/assets/13518486/14956646/1c644746-1081-11e6-897b-51d0a49fc263.png)

**Comment by iainbryson** [comment]
This area has been sigificantly altered and I think it may not be possible to reproduce the issue
