### ISSUE TITLE
Expired quiz doesn't show up in the list of expired quizzes

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#134]
* Create quiz for 10 minutes start/finish.
* Max time unlimited
* Set 1 attempt
* take quiz and let it run out

The quiz will then not show up in the list of expired quizzes as expected.

**Comment by iainbryson** [comment]
IIRC this is something which has been totally reworked in staging.  I’ll check to see if this works there.

**Comment by iainbryson** [comment]
Fix for #133 should fix this.
