### ISSUE TITLE
Clicking Visible also gives Modified state

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#135]
Clicking Visible should only give locked state, but it also gives Modified.

**Comment by iainbryson** [comment]
Can you provide a little more detail on this one?

**Comment by dtu-compute** [comment]
When you create a quiz and then make it visible, then it gets the state "Locked and Modified", which should just have been "Locked".

Modified is when the quiz file have been modified after it have been made visible, right?

**Comment by dtu-compute** [comment]
It happens for me in both cases.
