### ISSUE TITLE
Wrong max time in Q1501

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#137]
It said there was 1 hour and 5 minutes left, even though there was much less to 15:45 which was the end time.

**Comment by dtu-compute** [comment]
Max time were set to unlimited and the end time were set so the students had 1 hour. For a hand full of students the timer wend down to 54 minutes, and then stayed there. Reloading the page updated the timer, but it was with a wrong time left.

**Comment by iainbryson** [comment]
Cannot reproduce this, so closing.
