### ISSUE TITLE
Something wrong with hand in and needs review numbers

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#143]
In the below screenshot are there not the same numbers of students for each quiz, but "Needs review" is 213 for both of them.

![222](https://cloud.githubusercontent.com/assets/13518486/15142093/c7ca6534-16a3-11e6-8213-da272bccb265.png)

**Comment by iainbryson** [comment]
This should be resolved by the recent rebuild and testing of this area of the product.
