### ISSUE TITLE
Admin redesign

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#146]
Main changes compared to the current design:

* buttons in 3 rows above table instead of the left
* separate sort buttons (could be server side sort)
* all rows in the table are one line
* is classes just one, then write the class, otherwise put a drop down menu (non selectable) where the title of the drop down is the number of classes

Are there parts of this that would be difficult to make or produce ugly code?

![qqq](https://cloud.githubusercontent.com/assets/13518486/15185692/96699f4e-179a-11e6-8d62-d96f14654f79.jpg)

**Comment by iainbryson** [comment]
The first part of this is done: getting the buttons and the table rows on full-width lines. A couple of questions about the remainder.

For the sort, the implication of having it be a toggle button is that (1) there is only one order (descending or ascending) and (2) you can't sort by more than one criteria at once.  I can see how (2) may not be required, but (1) is questionable.

Other than that, everything else is implement as of now.

**Comment by dtu-compute** [comment]
Very nice!

Having the quizzes with the highest QID at the top ended up being the preferred sorting =)

It would however be a very nice feature, if the primary is the selected and secondary by QID. That would be very useful for Status and Visible.
