### ISSUE TITLE
Test 1: Why could some not take the quiz?

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#147]
When kschstu tried to take the quiz the Quiz button didn't do anything besides loading a bit in the browser.

We have now been told that some saw a very short glimpse of the quiz and then got a 404.

We then cloned the quiz and used class A instead and it worked for most. For those it didn't work for, had the same problem as kschstu and sometimes got the "Something wend wrong error".

A list of the username are at
https://github.com/dtu-compute/doc/blob/master/exam-tests.md

**Comment by dtu-compute** [comment]
Here is how to reproduce it on 2016-05-11 53a7b82.

* Clone Q1498
* Take the quiz as kschstu and just click Hand In.
* Click View results
* Click Back

Now you still have 1 attempt left, and when clicking on Quiz it just loads for a while without giving you the quiz.

Right now Q1506 is active for kschstu until 16:30 today, which have this issue.

**Comment by iainbryson** [comment]
Fixed (probably ;) with commit 02258f92a47e0e90f7b43f20f9cc53fdee1bee2b
