### ISSUE TITLE
Don't know option

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#153]
When clicking "New" there should be a check box with the text "All questions have a Don't know option".

When selected, a check box is added the bottom of each question in the quiz called "Don't know", which would dim and disable the question from being answered.

The purpose is that e.g. one course would like to give
* +3 points for correct answer
* -1 point for wrong answer
* 0 points for "Don't know".

Choosing "Don't know" should therefore also be in the exported json file. Right now there is `true`, `false`, `NA`, and perhaps `DONTKNOW` ?

**Comment by iainbryson** [comment]
How are the points to be specified?  Are they hardcoded?  Provided by a config file? Added to the quiz file?

**Comment by iainbryson** [comment]
Also: What is the behavior when taking the quiz?  When a student selects Don't Know, does it blank the answer (if any)? Does it disable the other answer controls?

**Comment by dtu-compute** [comment]
About points: The professor will write a R script with takes the export json file and post process it, where he will give 3 points when he sees TRUE, -1 for FALSE and 0 points when `DONTKNOW`. So it is done outside of the quiz.

> When a student selects Don't Know, does it blank the answer (if any)?

You mean if it have an influence on what is shown after handing in? If, then it doesn't effect the feedback level or behaviour. 

> Does it disable the other answer controls?

Yes, for that question. Selecting the "Don't know" checkbox should prevent the student from typing or selecting anything else for that question. Unticking "Don't know" should return the question back to normal.

**Comment by iainbryson** [comment]
> > When a student selects Don't Know, does it blank the answer (if any)?
> You mean if it have an influence on what is shown after handing in? If, then it doesn't effect the feedback level or behaviour.

No, I mean suppose a student answers a question, then hits "don't know". Do we have that partial answer?

**Comment by dtu-compute** [comment]
Ok, Then "Don't know" overrules.

The student should realise that there isn't a partial answer submitted as the radio button, check boxes, fill in the blank, free text etc is dimmed and not responding when "Don't know" have been checked.

When "Don't know" have been checked whatever the student might have selected or typed in that question should not be saved or submitted.
