### ISSUE TITLE
Unbundle copy images from quiz file parsing

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#154]
When the container is rebuilt, the images copied to the assets folder from the local git repo are removed.  Currently, they're only placed back there when the quiz is re-parsed.  We need a way for them to be recopied at container construction time, which will entail saving the original picture location.

**Comment by iainbryson** [comment]
Hi Martin.  I think this is very important; could you prioritize?

**Comment by iainbryson** [comment]
Another thing we should probably do is create a docker volume with the image assets so we don't have to recopy when we rebuild the containers...

**Comment by dtu-compute** [comment]
Yes, a volume sounds like a good idea.

A thing about volumes is that if you do `-v /vol/images:/dtuquiz/app/images`, where the first path is on the host, then docker won't allow that files are written to `/dtuquiz/app/images` during rebuild, as it will result in files being written to the host. I don't think it gives an error. It just doesn't do it.

**Comment by iainbryson** [comment]
I can create a new root under app/assets/quiz-images or something pretty easily.  I think that will work well.
