### ISSUE TITLE
Investigate persistence in sessions, especially w.r.t having multiple app servers (actual sessions for HTTP, https://github.com/websocket-rails/websocket-rails/wiki/Using-the-DataStore for web sockets)	[Perf/TaskPaper]  

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#172]

**Comment by dtu-compute** [comment]
If we end up in a situation where one server can't host it all, then it is a big thing, so let's wait with this one.

**Comment by dtu-compute** [comment]
Btw. When you say _servers_ do you then mean a piece of hardware or is a server a piece of software?

**Comment by iainbryson** [comment]
Not necessarily; I mean multiple rails instances, whether on the same host or multiple hosts (multiple hosts will require more work though)

**Comment by dtu-compute** [comment]
Ok, that would be super interesting to be able to use more cpu cores!

**Comment by dtu-compute** [comment]
Let's revisit this if we run into performance issues.
