### ISSUE TITLE
Investigate performance of loading MathJax off a CDN or NGinx. [Perf/TaskPaper] 

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#173]

**Comment by dtu-compute** [comment]
Is this a dup of #216 ?

**Comment by iainbryson** [comment]
Yes, it’s a subset.

**Comment by dtu-compute** [comment]
Ok, then I close it, as serving static files from nginx is cleaner, and it is not so important how much faster it is.
