### ISSUE TITLE
"Are you sure" modal if not all questions are answered

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#179]
A modal should appear when clicking Hand In and not all questions have been answered or clicked "Don't know", if that feature is enabled for that quiz.

It could e.g. say
```
You haven't answered all questions.

[Go back to quiz]    [Hand-in]
```

**Comment by iainbryson** [comment]
We already have a hand-in confirmation modal:
![image](https://cloud.githubusercontent.com/assets/1531103/18618474/644da40c-7d9c-11e6-8ccd-5e9bb9bcf744.png)

Do you want to add a new modal before or after this one, or simply a message to that modal?

**Comment by dtu-compute** [comment]
Good point. Let's add the extra text to the current modal.
