### ISSUE TITLE
Move known_hosts to /vol/quiz-keys/

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#183]

**Comment by iainbryson** [comment]
The problem with doing this is that the volumes aren't attached during build.

We could move adding the known_hosts to run-server.sh, which will have access to /vol/quiz-keys.

However, the purpose of this file is simply to allow git to ssh to github.  As such, it's not going to be a quiz-instance specific configuration.  It should let all quizzes point to the same github, so it ought to be the same everywhere.

To me, that implies it should be in the repo.  What do you think?

**Comment by dtu-compute** [comment]
Good point.

Right now it contains 6 hosts. Can all except `github.com` then be removed?

**Comment by iainbryson** [comment]
3 of those -- the IP ones -- are actually aliases for github, so keeping them be ok.  How about I leave them with a comment as to what they are?

**Comment by dtu-compute** [comment]
That would be perfect =)
