### ISSUE TITLE
Move challenge/ to /vol/letsencrypt ?

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#189]
Or should the quiz have its own `/vol/quiz-letsencrypt` ?

If the challenge is the one time use, then it can just be deleted from the repo I suppose?

**Comment by iainbryson** [comment]
The quiz doesn't need it's own ssl cert setup, so I can remove all the rails let's encrypt stuff.  It can just use vol/certs like all the other components.  And this doesn't hinder the separability of the quiz app as standalone -- you'd just need a /vol/certs and a let's encrypt to generate it. If you want me to add that to the quiz's docker-compose, I can do that (better to track with a separate issue, and leave this to remove the challenge endpoint and rails let's encrypt setup.)

**Comment by dtu-compute** [comment]
Great. I'll create a new ticket for that =)
