### ISSUE TITLE
Move certs out of repo

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#190]
The quiz doesn't need it's own ssl cert setup, so I can remove all the rails let's encrypt stuff. It can just use vol/certs like all the other components. And this doesn't hinder the separability of the quiz app as standalone -- you'd just need a /vol/certs and a let's encrypt to generate it. If you want me to add that to the quiz's docker-compose.

**Comment by iainbryson** [comment]
Already fixed.
