### ISSUE TITLE
Admin page flash notifications overlap in an ugly way

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#191]
![image](https://cloud.githubusercontent.com/assets/1531103/18036059/1f307fec-6d17-11e6-971b-3911cbffa332.png)

**Comment by iainbryson** [comment]
the lower, blue one is for "quiz updated".

**Comment by dtu-compute** [comment]
Is it by design that they stack and are off set?

**Comment by iainbryson** [comment]
That would be cool ;)  But no, they’re using two slightly different mechanisms for flash messages, one on the client and one on the server. And you cannot select between them to see previous messages (which would be a neat feature), so right now it’s just visual clutter without any benefit.

**Comment by dtu-compute** [comment]
I see =)

Can it be changed, so there is no bg colour and close button? That way the latest message will always override the old?

**Comment by iainbryson** [comment]
We can certainly do that.  But I think that makes it stand out more like a message when there’s a color hint and close, otherwise text in the nav bar might seem like part of the title rather than a transient alert.

The solution I was planning on was simply to have only one flash message at a time to prevent the overlap.

**Comment by dtu-compute** [comment]
Perfect. Please do that =)
