### ISSUE TITLE
Should config/mongoid.yml be considered a config file for /vol/config/quiz-* ?

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#193]
https://github.com/dtu-compute/dtu-quiz/blob/devel/config/mongoid.yml

**Comment by iainbryson** [comment]
This is a config file for a the Mongoid rails gem itself, rather than for the whole quiz app, so I think it makes sense to keep it internal to the project.  Does that reasoning seem right to you?

**Comment by dtu-compute** [comment]
Yes. I am closing =)
