### ISSUE TITLE
git rm -r nginx

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#194]
Instead of having a nested container have I created a new repo called dtu-quiz-nginx.

I am not quite sure how you it should be built in this case, so I prefer if you can update `docker-compose*`.

**Comment by dtu-compute** [comment]
Would it be a good idea to have a `components/` similar to dtu-enote for mongodb and nginx?

**Comment by iainbryson** [comment]
nginx isn't required for enote, only if you run the quiz independently.  It basically does the reverse proxy in the case where enote's reverse proxy isn't around.
