### ISSUE TITLE
Always show courses in drop down menu

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#195]
However I can’t add a new quiz to 01006 because there are no students.

Right now, we only show groups which have students in them in the form.

**Comment by iainbryson** [comment]
I'm not sure the text of the issue and the title match in this case.

The title seems to be about the courses dropdown.  But the text seems to be about the 'New Quiz' button.  Do you want to be able to create a quiz if there are no students?  Can we rely on the list of groups being complete if there are no students?

**Comment by dtu-compute** [comment]
I think it is about the case, where there is a course without students and there is no way to get to the admin interface for that course, because only courses with students are in the course select drop down.

Does that make sense?

**Comment by iainbryson** [comment]
We will show the course list for any course the user has a role in (admin/student).  So an admin should always be able to get to the admin page (please let me know if somehow you don't see that). However, that admin will not be able to create a new quiz unless there are students in some (any) groups.

**Comment by dtu-compute** [comment]
Ok, excellent. I am closing then.
