### ISSUE TITLE
View as Printable

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#200]
There should be a "As printable" or "Print" button the in View row of buttons, which renders a version of the quiz that is suitable for printing.

The purpose of that the professors would like to have printed paper versions of the quiz to hand out in case something breaks.

At the top of the page there has to be space for the student to fill out
- Name
- Course
- Student number
- Table number
- Date

**Comment by iainbryson** [comment]
Other than the extra header information, what else would you like in the print view?

**Comment by iainbryson** [comment]
Also, we know the course.  Should it just be printed, or do you really want a blank for the student to write it in?

**Comment by iainbryson** [comment]
With these changes, there's now a printable option and it looks like:

![image](https://cloud.githubusercontent.com/assets/1531103/23097094/00b89228-f5e0-11e6-8e94-b78078746120.png)

Did you have more in mind for this ticket?

**Comment by dtu-compute** [comment]
Ahh yes. Good point. It would be great if the course number and title are already filled out.

Looks really good!
