### ISSUE TITLE
Export as JSON and as CSV

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#202]
Right now the admin can only export to json.

It would be good to have a "Export json" and "Export csv" button, where the first is exactly like the one now and the second pulls in the R script from https://github.com/dtu-compute/dtu-enote-json2csv and executes it on the json file and return the csv.

**Comment by iainbryson** [comment]
Let be double check to make sure I'm not overthinking this one.

You want the quiz image to clone json2csv and install R, then run json2csv.R on the json file as a new 'export to csv' option.

Is that correct?

**Comment by dtu-compute** [comment]
Yes, R needs to be installed in the quiz container, so it can use the script in json2csv to output the csv file.

Some of the professors will have commit access to json2csv, so they expect that if they change something in the R script, then pressing the "Export csv" will use the latest version in json2csv.

The R script probably needs to be modified to fit better for this purpose.

**Comment by dtu-compute** [comment]
Very nice patch!

As an extra feature can repo and filename be taken from e.g. `/vol/config/json2csv.yaml`

```
repo: https://github.com/dtu-compute/dtu-enote-json2csv
file: json2csv.R
```
