### ISSUE TITLE
Pictures not showing up

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#205]
02417 had an issue with Q16, where pictures wasn't shown. He made a clone and still no images. He then added a space in some text, and the images appeared.

https://github.com/dtu-compute/02417/commits/master

**Comment by iainbryson** [comment]
Hmm.  I think there might be a design hole here.

We check and copy the images when we parse the file, which maybe explains why “adding a space” (and presumably update) fixed it.  But we don’t track uploads of images as a potential trigger for re-copying.

How would you like to have this work?  What would be the typical professor workflow?  Right now things “should” work if the professor adds a bunch of picture references to the quiz, commits and pushes the image files, then commits the quiz, then updates the quiz.

But not following that flow might result in problems.  An alternative would be have a “update images” button.  Or to update images always when publishing or “viewing as…"

**Comment by dtu-compute** [comment]
Ok, so right now clicking "Update" also takes in any new images from the repo? If, then that is exactly what we want.

However when a quiz have been made visible, the quiz should ignore any image changes in the repo.

**Comment by iainbryson** [comment]
Almost.  Currently update will move the images only if there commit id of the quiz template is different from what we’ve got in the DB.  i.e. if the quiz template has been updated.

Yes, once it’s visible we don’t update.

**Comment by dtu-compute** [comment]
When you say quiz template, then you mean `template.quiz`?

**Comment by iainbryson** [comment]
No, sorry, that was unclear.  The .quiz file itself.  Essentially we only check for new images and updates when we see the .quiz file has changed, not when any new/deleted files happen in the images.

**Comment by dtu-compute** [comment]
The safest would probably be renaming "Update" to "Updates quizzes" and have an "Update images".

Would it be messy to have a check when clicking Visible which said something like?:

"
There are newer images in the repository than the currently used images in the quiz.

To update to the latest images, click Cancel and then Update images.
To continue without updating the images click OK
"

**Comment by dtu-compute** [comment]
Thinking about it for a little while, it probably is best to update images automatic when clicking View as and Visible. So not using my previous comment =)

**Comment by iainbryson** [comment]
That’s straightforward enough.  So, when a quiz is made visible we can (1) perform a git pull (2) copy all the images

What happens when (2) fails?  i.e. an image isn’t present. Right now we don’t treat that as a hard failure, but perhaps we should.

**Comment by dtu-compute** [comment]
Excellent.

That would be a great if it hard failed on missing images.
