### ISSUE TITLE
Needs-Review Design Issue

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#210]
While working on the getting the manual question scoring features working, I realized a flaw in the design.

The design has the user paging through questions one by one, the set of which is determined by group, question number and whether the question has been scored.

While looking at the already-scored questions ("done") works fine since the count of those won't change during iteration, that's not the case for yet-to-be-scored ("New") questions.  i.e., if you set the score of the first question, then move to the second, the 1st question is no longer in the "New" set, so we should really go to #2.

Currently this is hacked by always going to page 1.  We lose the ability to iterate (and not score) the questions.

The only way around this would be to maintain a session list for New, and keep questions in that list as long as the current dialog is up.  I think this can be done, but I'm not 100% certain.  Or we can not allow iteration for "new" questions, basically making the current hack the design (and removing "question #" from the title, since it'll make no sense)

How do you want to proceed?

**Comment by dtu-compute** [comment]
Ok, so if I have understood the problem then is because the Review code stores the new questions in an array and removing an element will change the index?

If, would it be expensive to not store the new questions, but always do a search?

In principle multiple reviewers could score the new questions at the same time.

**Comment by iainbryson** [comment]
Aside: worth fixing #23 at the same time.

**Comment by iainbryson** [comment]
Actually, the problem is that we always do the search rather than storing a specific array.

Because we search and reload the next question to be reviewed after every review, the following happens: say we have 10 questions to review.  We start the review and get the first question.  We review it.  Now on reload, we only have 9 questions.

Now, because the client just reviewed question 1 of 10, we seek page 2.  But page 2, when we get it, is now page 2 OF 9, not the original 10, because the first one is no longer "to be reviewed".

That's the essence of the rpoblem.  As you point out, it makes things more robust to multiple editors.  But it also makes it harder to maintain context for a single editor.

So we can do in two directions: have the client get the full list of 10 and move through it like a user would expect.  This causes potential for collision, which won't be fatal -- we can always just reload)

Or we can always only show the "first" un-reviewed question and have a "X remaining" notice.

Right now the UI design is a messy mix.  If we displayed the remaining it would go from 1/10 to 2/9, to 3/8, etc... which makes no sense.

**Comment by iainbryson** [comment]
And actually #168 is related to this also

**Comment by dtu-compute** [comment]
If the following is possible, then it would be perfect:

> Or we can always only show the "first" un-reviewed question and have a "X remaining" notice.

**Comment by iainbryson** [comment]
Perfect!  That means for “new” questions, the forward and backward arrows are not needed and we can just go with showing the “current” one and indicate the number of remaining questions.

**Comment by dtu-compute** [comment]
Great.

The purpose of the back arrow is "Ups, I just scored the question wrong, and I want to go back and change it." Can that situation still be handled somehow?

**Comment by iainbryson** [comment]
Ah, so then we need to consider more.  That functionality can’t really be implemented without _some_ kind of caching.  In the current no-cache model, we don’t have a way to go back because once we’ve marked a question, it’s no longer in the set of “new” questions to be reviewed.

So to implement what you describe, we’ll need to take a snapshot of all the un-scored question when the user clicks filter combination boxes.  We’d then focus on that set — which would include unsecured questions as well as any scored during that session.  dismissing the dialog or changing the filters would reset the snapshot.

But there’s another issue: we’ve implemented a 60s lockout on changing a score.  So if a grader had second thoughts about a question and wanted to go back, well, they’d have to wait.

**Comment by dtu-compute** [comment]
How difficult would it be to modify the current logging to?:

* a global review log per course
* admins and reviewers can see all entries
* instead of a back button the reviewer would exit scoring questions and click "Log" in the View section and he could click on the question he wants to edit.

Could the 60s be deactivated then no one is having the question open?

**Comment by iainbryson** [comment]
Technically this should be feasible.  I’m not so certain about the usability, I think we’d need to clarify the design a little more.  Specifically, is it ok to have that many steps to just fix an error?  They can do a similar thing now by just flipping over the the “done” filter. Also “Having the question open” is a little tricky.  The server will know who it sent the question to, and when. But not necessarily when they close it or stop looking at it.  We can work around it by having an explicit checkin/checkout semantic with timeout, perhaps.

**Comment by dtu-compute** [comment]
Yes, the global log is not an easy solution for a simple "ups clicked the wrong button" mistake.

If someone scored a question wrong, can they then just go to "Done" and re-score it as it is now? That would be the preferred solution. Especially if "Done" is sorted by last edit time stamp.

> Also “Having the question open” is a little tricky.  The server will know who it sent the question to, and when. But not necessarily when they close it or stop looking at it.  We can work around it by having an explicit checkin/checkout semantic with timeout, perhaps.

I see. It would require a websocket or similar...

But if I have understood the problem correct, then the Done list can always be up to date, if the server know which question it have handed out for scoring to who and when.

Example:

* at 13:00:00 I get question XXX for scoring.
* at 13:00:11 I score it and go to next question
* at 13:00:30 I enter the Done list
* the server know it have handed out question XXX to me at 13:00:00 and it got it back, so it can ignore the 60s timeout, and add the XXX question to the Done list

Or?

**Comment by iainbryson** [comment]
> On Nov 2, 2016, at 7:04 PM, dtu-compute <notifications@github.com> wrote:
> 
> Yes, the global log is not an easy solution for a simple "ups clicked the wrong button" mistake.
> 
> If someone scored a question wrong, can they then just go to "Done" and re-score it as it is now? That would be the preferred solution. Especially if "Done" is sorted by last edit time stamp.
> 
> 

Yes, that should be totally possible.

> Also “Having the question open” is a little tricky. The server will know who it sent the question to, and when. But not necessarily when they close it or stop looking at it. We can work around it by having an explicit checkin/checkout semantic with timeout, perhaps.
> 
> I see. It would require a websocket or similar...
> 
> But if I have understood the problem correct, then the Done list can always be up to date, if the server know which question it have handed out for scoring to who and when.
> 
> Example:
> 
> at 13:00:00 I get question XXX for scoring.
> at 13:00:11 I score it and go to next question
> at 13:00:30 I enter the Done list
> the server know it have handed out question XXX to me at 13:00:00 and it got it back, so it can ignore the 60s timeout, and add the XXX question to the Done list
> Or?
> 
> 

Yes, although the phrasing “Done list always up to date” is a little misleading.  The done list is queried _when_ you switch from New to Done, so there’s nothing that’s kept up to date. 

It should be easy to allow the user who scored the question to re-score it within 60s, but not any others.  Would that solve the design concern?

**Comment by dtu-compute** [comment]
Very nice. That would be perfect.

**Comment by dtu-compute** [comment]
I am closing this one, as the Review part of the quiz haven't been used yet, and wonder if it will =(
