### ISSUE TITLE
Admin page and menu shrinks wrong

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#213]
![1](https://cloud.githubusercontent.com/assets/13518486/21714873/87615a40-d401-11e6-913b-26e8b836cdb9.png)

**Comment by iainbryson** [comment]
What design do you want for the buttons?  Do you want them to get smaller (but stay in a row), or create multiple rows for each type of operation?

**Comment by dtu-compute** [comment]
Multiple row would be great.
