### ISSUE TITLE
Picture links break when cloning

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#221]
* In Q53 `boxplot.png` were used.
* Cloned to Q54. 
* Q54 gives error `Picture '/assets/quiz-assets/images/02323/53/images/boxplot.png' not found in repo`
* Q54 View Source gives `src="/assets/quiz-assets/images/02323/54/assets/quiz-assets/images/02323/53/images/boxplot.png"`
* Following works `https://quiz.compute.dtu.dk/assets/quiz-assets/images/02323/54/images/boxplot.png`

**Comment by dtu-compute** [comment]
Just making a note here, as maybe this will go away then this tickets is fixed.

Q61 in 02323 doesn't have the picture `/assets/quiz-assets/images/02323/61/images/boxplot.png`

https://quiz.compute.dtu.dk/assets/quiz-assets/images/02323/61/images/boxplot.png doesn't exist either.

**Comment by iainbryson** [comment]
Fixed (in devel). LMK if you want to hotfix to 2016. It should be a pretty safe fix.

**Comment by dtu-compute** [comment]
It would be an appreciated fix for sure =)

If you prefer to hotfix now, then I can test Sunday and Monday, or we can save it for when the MathJax rendering error is solved perhaps?

**Comment by iainbryson** [comment]
I was thinking to do this when we had more mathiax rendering information.

It sounds like from this morning though we might need to add more logging (to the course Web site) and the ability to delete/change visibility for courses in the visible state.  Is that correct?

**Comment by dtu-compute** [comment]
I am not sure I understand what you mean by "ability to delete/change visibility for courses in the visible state".

**Comment by iainbryson** [comment]
I was referring to the catch-22 of not being able to delete quizzes because they are visible, but not being able to make them invisible because they are in an error state.

**Comment by dtu-compute** [comment]
Yes okay =) And the fix/hack was to not check for valid images when deleting?

**Comment by iainbryson** [comment]
Yes.  Do you want me to add that to the quiz for today’s deployment?

**Comment by dtu-compute** [comment]
That would be great =)

**Comment by iainbryson** [comment]
Done.
