### ISSUE TITLE
Direct link to a quiz

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#225]
The intention was that the professors should always link to quiz.compute.dtu.dk, but how difficult would it be to make direct links to a quiz?

**Comment by iainbryson** [comment]
How would the design for this work?

Say a professor passes a like quiz.compute.dtu.dk/Q5, what do you want to happen?

Attempt to start a new quiz (or resume an old quiz)?  Or maybe a a new page which contains just information about the quiz and the QUIZ/RESULT button line from the student quizzes page?

**Comment by dtu-compute** [comment]
Typing quiz.compute.dtu.dk/Q5 would be the equivalent of clicking the "Take quiz button" or can that back fire somehow?

**Comment by iainbryson** [comment]
I don’t see any problems at the moment.

**Comment by dtu-compute** [comment]
Great. Then let's go with that =)

**Comment by iainbryson** [comment]
Actually, I think this already works to some extent:

```
https://quiz.docker.local/new-quiz/173
```

Is the URL which will take you to the quiz launcher, i.e. this page:

![image](https://user-images.githubusercontent.com/1531103/27118240-b14dd594-50da-11e7-8d80-81a124be4004.png)

Is that enough?  

Should there be a UI affordance on the admin page to let a prof copy such a link?

**Comment by dtu-compute** [comment]
That's exactly what they are looking for =)

A "Quiz Link" button under View would be great.
