### ISSUE TITLE
"Not yet" button takes the student back to course selection

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#232]
Clicking "Not yet" in the modal that appears when clicking Quiz should close the modal, but instead it takes the student back to selecting courses.

**Comment by iainbryson** [comment]
To be clear: "Not Yet" should take a student back to the quiz selection page, correct?

**Comment by dtu-compute** [comment]
Yes, the quiz selection page  for the course the student selected.
