### ISSUE TITLE
Prevent authors from going to the student quizzes page

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#234]
> > Is this something you want to add in 2016?  

> Yes, if not the final solution, then a fix of some sort.

> > I suspect this will take some design thought.  In particular, for scoring, are authors considered part of the class or not?  Can authors review their own quizzes?

> Hmmm. Good questions. It is not really important that the authors can take the quizzes. I just figured that was the easiest to code.

> > For 2016, maybe the most we can do safely is prevent users from getting into this.  Authors still can look at the quizzes from the admin view, but I suspect that they cannot take the quizzes safely.

> Perfect solution! =)

> If that could come in 2016 then it would be really good.

**Comment by iainbryson** [comment]
Note: After this particular issue is resolved, it'll be worth addressing the issue of permissions more holistically: https://github.com/dtu-compute/docs/blob/master/permissions.md

**Comment by iainbryson** [comment]
Committed to 2016.

**Comment by dtu-compute** [comment]
The professors say Authors and Admins should be able to submit quizzes if the exported json have a column that says which role the submitter have, so they can filter out authors and admins when parsing the json.

The stats on the admin page do they only use to get an idea of how active a quiz is.

**Comment by dtu-compute** [comment]
What ended up being the solution to this?
