### ISSUE TITLE
Need a second test course

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#237]
Some of the bugs we appear to have (i.e. with #235 ) appear to be involved with cross-course permissions.  So for our testing, it would be ideal to have a second test course, maybe `00001` to complement the existing one `00000`.

**Comment by dtu-compute** [comment]
Sounds good!

https://github.com/dtu-compute/docs/blob/master/Add-new-course.md is the procedure to create a new course. But I see now that it is missing certificate part. I recall you sent me that in an email, so I'll put that in tomorrow.

I'll follow up on the 4 test accounts as well =)

**Comment by iainbryson** [comment]
Perfect! Thanks Martin

**Comment by iainbryson** [comment]
I think this works right now.  The only other piece would be to create it fully in campus dumper.  Is that possible?  Is not, we can close this now.

**Comment by dtu-compute** [comment]
iaibrys, iajbrys, enotem[a-d] should now have received an email for joining enote-development. It is not exactly a course, but extracting members from this group should be identical.

**Comment by iainbryson** [comment]
Is there a set of keys for the -website files and pages repos?

```
/website-keys/00001-files.pub
```
?

**Comment by dtu-compute** [comment]
Ups, the course wasn't public, now it should be.

Admins: iaibrys, hench, mttj, enotema
Authors: enotemb
Users: iajbrys, htech, enotemc, enotemd

**Comment by dtu-compute** [comment]
On production the keys are in 

```
/vol/quiz-keys/00001.pub
/vol/website-keys/00001-files.pub
/vol/website-keys/00001-pages.pub
```
they should also be on staging and devel2.

**Comment by iainbryson** [comment]
I don't know that this is needed; Let's close it out now and then see if the need re-emerges.
