### ISSUE TITLE
Insert new/clone in top of admin menu

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#242]
When making a new or cloning a quiz it would be convenient if it were inserted at the top of the list.

**Comment by iainbryson** [comment]
How do you want this to interact with the existing sorting?  The easiest way to implement this would be to force any reload after a new quiz has been created to change the sort order to quiz id descrending, which would put the new quiz at the top.

But it would also change any order the user already set.  Is that ok?

**Comment by dtu-compute** [comment]
Prefect =)

**Comment by iainbryson** [comment]
Fixed.
