### ISSUE TITLE
Header overlaps drop down menu in full screen

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#253]
Only in full screen. With a small screen width it is fine.

![screenshot from 2017-09-06 13-42-51](https://user-images.githubusercontent.com/13518486/30110207-9648d304-9309-11e7-9551-d821d9b2ea95.png)

**Comment by iainbryson** [comment]
Does this still repro for you with current FF?  On my machine (macOS, FF 59.0.2) it works properly full screen on staging:

![image](https://user-images.githubusercontent.com/1531103/38165542-fb0e131e-34c9-11e8-8739-837d5e0e4a88.png)

**Comment by dtu-compute** [comment]
Works here too =)
