### ISSUE TITLE
Git commits should have quiz title

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#258]
When creating a quiz now the commit message is e.g. `New quiz file for new quiz Q208`.

It would be useful if it could be `Create quiz_number quiz_title`

When deleting a quiz now the commit message is e.g. `Deleting quiz file`.

It would be useful if it could be `Delete quiz_number quiz_title`

**Comment by iainbryson** [comment]
Fixed in the last commit-storm.
