### ISSUE TITLE
Remove Export to csv

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#261]
Let's only support json output and if anyone want csv, then we can write a json2csv script to execute on their client.

**Comment by iainbryson** [comment]
Martin,  If you're certain you want to do this, it makes sense to do part of it early.  The base image will need the heavyweight R and R-dev if we don't since we use R to transform json to csv.

**Comment by dtu-compute** [comment]
Ok, then let's make this also a Sub milestone A.

**Comment by dtu-compute** [comment]
Or just ignore its dependencies now knowing this ticket will come later. That's also fine =)

**Comment by iainbryson** [comment]
It’s a little more complicated since we also have tests and setup which
depend upon it.  Anyway R is there now and we can remove it later.

**Comment by dtu-compute** [comment]
Yes, let's remove it when it fits in.
