### ISSUE TITLE
Mass submit after network down and no save to json

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#3]
Can be following be done?:

A quiz is set for an hour, but the network is down after the first 30 minutes, and doesn't come up again for many hours. The student therefore leaves with the quiz not being submitted. The morning after the network/server is online again.

If the professors asks all students to login to the quiz again the next morning. Will the quiz then be submitted?

If that is the case, then he would like that the "Save to json" button and feature to be removed.

For the record, I like the save to json feature =)

**Comment by iainbryson** [comment]
At the moment, the design is that there is very little difference between the "handed in" a.k.a. submitted state and the "expired" state.  Either way the quiz instance is locked, either way the quiz has the latest answers in it and it will get scored the same way.  The only difference is that the user pushed the button to hand it in.

So in the scenario above, there isn't anything the students can or need to do the next day.  The quiz results will simply be there. I suppose they might want the option to say that the quiz didn't have all their answers so a review might be in order.

Does that sound reasonable?

**Comment by dtu-compute** [comment]
Yes, that makes sense.

The professor prefers that the students make a PDF (CTRL-p) of the quiz with their answers in the above case instead of json files.

> I suppose they might want the option to say that the quiz didn't have all their answers so a review might be in order.

Would it be possible to have the server log the last time it had seen connection to the client?

The student could of course just disable the NIC to simulate a network failure during the quiz =), but if many have the same date and time for "last seen for this quiz" and "last seen in general", then I suppose it would have to be an University issue and not student computer issue?

**Comment by iainbryson** [comment]
Keeping track of connectivity on a per-client basis would be more work, and require a bit of research.  I think it's possible, assuming there are no confounding issues like NAT.

There is already a last update time on every quiz.  We could use that pretty easily to determine if there was any obvious "dead time" where students stopped updating quizzes in advance of the end time.

And a further extension of that would be to log all transactions with the quiz.  That would make the picture even clearer and really show differences between individual students and the whole population.

And to be precise: the main difference between the 1st point and the last 2 is whether we're monitoring access at the CLIENT level or the QUIZ level.

**Comment by dtu-compute** [comment]
Then let's wait for now with keeping track of connectivity on a per-client basis.

If "last update time on every quiz" could end up in the CSV file, then that would be great. Is that for all students or per student? The analysis will I let the professors do, so the system doesn't make these decisions. 

> And a further extension of that would be to log all transactions with the quiz. That would make the picture even clearer and really show differences between individual students and the whole population.

An interesting idea for sure, and I would imagine the statistics professors would data mine it for all sorts of info =) I suspect that it would make the CSV output a lot more difficult to analyse for those that just want to know the grades for each student? If that is the case, then it would be better to wait and see if they request this feature.

> And to be precise: the main difference between the 1st point and the last 2 is whether we're monitoring access at the CLIENT level or the QUIZ level.

I'd say if we have QUIZ level now, then let's write that in the CSV file, and see if there is a demand for CLIENT level =)

**Comment by iainbryson** [comment]
It should be easy to add last update time to the csv.  If we go down a the route later of having all the transactions logged, I'd say that's a different csv...

**Comment by dtu-compute** [comment]
Great. A transaction log in its own file would be perfect, but let's see first if there is a demand first.
