### ISSUE TITLE
Changes to dtu-data

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#32]
`xxxxx-groups.yml` and `xxxxx-users.yml` should not be in the repos, but directly in `dtu-data/`. The campus dumper will dump the files in `/root/dtu-quiz/dtu-data`. This will also prevent the professors from editing the memberships, which they have to do through the Campus database.

The content in `courses/` should be in the parent dir. I.e.
```
cd /root/dtu-quiz/dtu-data
mv courses/* .
rm -rf courses
```

**Comment by iainbryson** [comment]
I’ve moved the  -groups and -users.yml to dtu-data.  However, do you really mean to delete courses?  It’s where I’m storing the keys and the course repos.

Regards,
— Iain

**Comment by dtu-compute** [comment]
Great.

On the second line I `mv courses/* .` =)

I just prefer to not having many sub directories. so `keys/` would be in `dtu-data`.
