### ISSUE TITLE
Update gives "The operation failed".

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#33]
After I edited a quiz and made a syntax error in the quiz, I got "The operation failed" when clicking Update.

**Comment by iainbryson** [comment]
This appears to be a result of failing to process empty group lists properly.

So we need to decide to either accept empty group lists, or disallow them from being created.

I, [2016-03-25T21:20:36.896071 #81]  INFO -- : Completed 500 Internal Server Error in 25ms
F, [2016-03-25T21:20:36.897518 #81] FATAL -- : 
NoMethodError (undefined method `each' for nil:NilClass):
  app/controllers/quiz_templates_controller.rb:85:in `update_quiz'


I, [2016-03-25T21:20:44.365315 #81]  INFO -- : Started GET "/courses/00000/quiz_templates/update/1034" for 83.91.11.86 at 2016-03-25 21:20:44 +0000
I, [2016-03-25T21:20:44.

**Comment by dtu-compute** [comment]
Let's make them required. I just sent the following on email (or I hope I just did):

I think we should make the following required:

* quiz name
* start time
* end time
* max time
* attempts
* groups
