### ISSUE TITLE
Quiz form has quiz creator field.  Why not just populate that from the logged in user?

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#35]

**Comment by dtu-compute** [comment]
Good idea.

**Comment by dtu-compute** [comment]
Now when I think about, it don't think this field would get used, as even on the mat1 course it is always the professor of the course that makes the quizzes. I bet they would use the comment feature in the quiz language to write things like that, if they should need that one day.

Let's remove it, and add it, if they request it for the 2017 version =)
