### ISSUE TITLE
How do quiz files get selected?

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#4]
In looking over the spec here: https://github.com/dtu-compute/doc/blob/master/1-quiz.md#edit--new-quiz-modal and implementing it, the one piece which isn't obvious is how to select the quiz file for the new quiz.

I can imagine a few options:

(1) The dialog searches the repo for all the .quiz files and presents them in a combobox
(2) The dialog creates a new empty quiz file when it gets saved, called QNNN.quiz.  In the case of name collisions we have to chose between overwriting and generating a fresh name (QNNN_2.quiz, e.g.)
(3) A mix -- the options with (1) appended with a "new" option which does 2

I guess it depends on whether you expect (and want to support) authors creating and committing their quizzes independently of the system.

**Comment by dtu-compute** [comment]
The authors are not allowed to create quizzes outside of the system, as it could give QID conflicts. So it almost your option 2, but the filename in the git repo for the new quiz is the QID number followed by `.quiz`.

The quiz won't be empty when clicking New, but

`New` creates a new quiz where it uses the template.quiz as described in the section "How to create a new course". The QID of the new quiz will take the next available number from the global QID counter. This number is uniq across all courses. The filename in the git repo for the new quiz is the QID number followed by `.quiz`.

My idea were that different courses would like to use their own quiz template, as there are likely many things they can copy/paste to save time.

**Comment by iainbryson** [comment]
OK.  That makes sense.  The implication is that the server will need to commit and push the new quiz file, correct?

**Comment by dtu-compute** [comment]
Yes, and it gets the template file from the course git repo. So if `template.quiz` is missing from the repo, then an error should be thrown.
