### ISSUE TITLE
Lock quiz after Visible have been clicked

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#42]
When Visible have been clicked, DTUquiz will never read the content of that quiz again.

When clicking Visible from unticked state it would be great to have a modal that says something like "Clicking OK now will make the quiz available to the selected groups and the quiz cannot be edited any longer."

When clicking Visible from ticked state it would be great to have a modal that says something like "Clicking OK now will take the quiz offline for all students and it is not possible to make the quiz online again."

**Comment by iainbryson** [comment]
Once the quiz has gone from visible -> not visible, should edits be allowed?  Since it'll not be possible to make it visible again according to this enhancement, I suppose it should be in some kind of readonly mode forever.  Is that your intent?

**Comment by dtu-compute** [comment]
Yes, that is the idea. Especially to prevent anyone from thinking, that they can just do a quiz and small edit to a Visible quiz and then make it online again. It should be clear to the quiz maker, that hitting Visible is a point of no return.
