### ISSUE TITLE
Edit Meta should not be allowed when Visible have been clicked

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#47]

**Comment by iainbryson** [comment]
We should design this more thoroughly in combination with #42:

* When it’s visible:
	Edit Meta should not work
	Update quiz should not work (?)

I think clone should not keep the visible status of the clonee if it’s irreversible — i.e. any quiz that is cloned starts off with visible == false.  How does that sound?

**Comment by dtu-compute** [comment]
Yes, great idea.

Perhaps we should bring "View Source" back, and change it so it displays the quiz in raw mode instead of Edit mode. E.g.

https://raw.githubusercontent.com/dtu-compute/00000/master/Q1051.quiz?token=AM5GlhpkF_nfdohOgJ3sBvHex6cufJ1sks5XD4RSwA%3D%3D

That way we can also deny Edit Quiz when Visible have been clicked.

**Comment by iainbryson** [comment]
We could do that, or we could simply make edit quiz go to the raw view if the quiz is not editable.  Which would you prefer?

Ideally, when each quiz is selected, the buttons get disabled and/or the titles change (e.g. for a non-editable quiz, the “Edit Quiz” button changed to “View Quiz”).  But that would best be a separate task, as it’s larger.

**Comment by dtu-compute** [comment]
Great if you can disable Edit Quiz if Visible have been clicked for a quiz. That saves us from a modal.

We better not change the text (or the action behind the button) on the buttons depending on which operations are possible for the selected quiz. I expect that will create confusion.

So if we can bring back the View Source in raw form, then that would be the preferred solution.

**Comment by iainbryson** [comment]
OK.  For symmetry, how about Edit Quiz becomes Edit Source and we bring back View Source?

The disabling issue would be better to track as a separate issue.

How does that sound Martin?

**Comment by dtu-compute** [comment]
2x perfect.

I'll create an issue for the disable of buttons.
