### ISSUE TITLE
Is the admin console checkbox single select?

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#5]
After getting part way through the implementation, it occurred to me that the spec is not specific on this point.  Can you select more than 1 row?  It would complicate things (we'd need to define the behavior which happens if more than one quiz goes "Edit Meta" for instance) and I don't think you'd gain a lot from it.

Thoughts?

**Comment by dtu-compute** [comment]
The plan was that multiple can be selected and depending on which button you click, you will either get the action on all the selected rows, or a modal that "only one can be selected for this action".

But you are actually right. It would only be delete that would benefit from this, so not a good idea, if it complicates the code.

Would it be possible to remove the "Select checkbox" and the Select column, and then highlight the row when clicking on it to indicate that it is now selected? Just like in the quiz.

**Comment by dtu-compute** [comment]
If that is possible, then it should also be possible to unselect a row by clicking on it again.

I write single click, but if double click is more user friendly, then let's do that.

**Comment by iainbryson** [comment]
That’s fair.  I can make it select the whole row.

If you have the “only 1 at a time” the code isn’t that complex, but the UI
becomes cumbersome: Instead of having the selects be mutually-exclusive,
you have to deliberately de-select when you change which quiz is selected.
And for almost all the options you’d have to do that.  Instead, if
selecting a new row makes the previously-selected one unselected, things
are simpler.

How does that sound?

On Wed, Feb 17, 2016 at 5:23 AM, dtu-compute <notifications@github.com>
wrote:

> If that is possible, then it should also be possible to unselect a row by
> clicking on it again.
>
> I write single click, but if double click is more user friendly, then
> let's do that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtu-compute/dtu-quiz/issues/5#issuecomment-185203102>.
>



-- 
— Iain

**Comment by dtu-compute** [comment]
> Instead, if selecting a new row makes the previously-selected one unselected, things are simpler.

Let's do with that =)

Would it be possible to to de-select the selected row by clicking on it again?

**Comment by iainbryson** [comment]
Yes, that’s straightforward too.


On Wed, Feb 17, 2016 at 11:11 AM, dtu-compute <notifications@github.com>
wrote:

> Instead, if selecting a new row makes the previously-selected one
> unselected, things are simpler.
>
> Let's do with that =)
>
> Would it be possible to to de-select the selected row by clicking on it
> again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtu-compute/dtu-quiz/issues/5#issuecomment-185354779>.
>



-- 
— Iain
