### ISSUE TITLE
Update should update all quizzes

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#53]
Right now one have to select a quiz and then click Update.

Would it be possible that selecting a quiz is not needed, and clicking Update will update all quizzes?

**Comment by iainbryson** [comment]
Let's design this a little more thoroughly.

In the case of errors/success, how do you want to proceed? (1) Just refresh with latest state (2) Have a status indicating number of success/failures (3) Highlight the quizzes whose statuses have changed, (4) other?

Also, do you want to update _all_ the quizzes, or just those on the same page?   Either way the operation will take quite a long time, so it might be best to have a dialog for it, with a progress display.

**Comment by dtu-compute** [comment]
Now I am just thinking loud, so correct me where needed.

What if Update does a `git pull` and then does a `git diff` and those quiz files that have changed since last Update AND are initially created by dtuquiz gets re-parsed.

In case of errors, the user get a "update success" and each quiz with errors gets their status changed to ERROR.

Make sense?

**Comment by iainbryson** [comment]
The problem with this is that right now there’s no guarantee that what’s “currently” in HEAD is actually in the system, so we could miss things.

To do a diff, we need to implement the other issue — #58 — or a variant of it, to keep the repo and the app in sync.  And that implies either implementing the full file compare/diff. Or the alternate idea of using the commit hashes.  Either way, the app needs to start keeping track of which files it has actually imported, something it does not currently do.

The question then becomes, do you want to implement #58 first (i.e. make it IMPORTANT), or do #53 in brute force fashion first?

activate your account <https://itunesconnect.apple.com/itc/static/activation?dsId=283543350&providerId=118180299&key=2061ab8dcceaf46121078cda9bb05da7>

**Comment by dtu-compute** [comment]
You mean in the case, where someone edits a quiz file and forgets to click Update? I don't think we can prevent this from happening.

> Either way, the app needs to start keeping track of which files it has actually imported, something it does not currently do.

Ahh, so by having to select a quiz you prevent externally created quizzes from entering the admin panel?

Yes, the app should keep track of which quizzes it have created and which that have been deleted, so old QID's can't be reused.

#58 is now marked as important.

> or do #53 in brute force fashion first?

#53 is this ticket. Did you mean that? If, then I don't quite understand it.
