### ISSUE TITLE
Admins are also students?

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#54]
How difficult would it be to implement that by being admin you also get the option to login as student?

I.e. in the course select drop down it would have

01005 (admin)
01005 (student)

Would it give some conflicts or ugly code?

**Comment by iainbryson** [comment]
Would it be acceptable for campus dumper to output user and administrator for every administrator?

**Comment by iainbryson** [comment]
Also: is this the case for authors too?
