### ISSUE TITLE
Maintenance rake command

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#55]
We could maybe start outside the system with a maintenance rake command which checks for orphan files, missing files and unimported changes — along the lines you suggest below.

Could you make a maintenance script which when executed (by me after I
have `docker exec ...` into the container) check for quiz orphans in the
DB and list them? if I want to delete one, then I would do

./maintenance.rb --db-delete #quiz number#

(It should not allow me to delete a valid quiz.)

and similar it could give a list of repo quizzes (and e.g. pictures in
the root of the repo, which should not be allowed and are therefore
orphans) that have been created outside of DTUquiz and perhaps an option

./maintenance.rb --repo-delete #filename#

That way I can put it in cron, and have it send an email if anything
should appear in the DB.

**Comment by iainbryson** [comment]
To cost this, let's figure out a list of commands.  Here is what is currently available:

```
rake dtuquiz:check_all_stats                    # [VALIDATION] validate statistics for all quizzes
rake dtuquiz:check_stats[quiz_no]               # [VALIDATION] validate statistics for the given quiz ID
rake dtuquiz:copy_images                        # [MAINTENANCE] publish images from repo to website
rake dtuquiz:destructive_resync_quizzes         # [MAINTENANCE] destructive resync quizzes (deletes quizzes which don't belong on disk)
rake dtuquiz:dump_user[user_id]                 # [DEBUGGING] dump all the information about a given user
rake dtuquiz:force_resync_quizzes               # [MAINTENANCE] force resync of quizzes
rake dtuquiz:generate_instances                 # [TESTING] generate random submissions for users
rake dtuquiz:purge_instances                    # [DESCTRUCTIVE] delete all quiz submissions from the DB
rake dtuquiz:recreate_quizzes                   # [TESTING] recreate quizzes in the DB based on quiz files in the repo, using random end times, visibility, full screen,...
rake dtuquiz:refresh_quizzes                    # [MAINTENANCE] resync quizzes (same as update in quiz admin UI)
rake dtuquiz:score_randomly[quiz_no,pct,count]  # [TESTING] randomly score manual questions from submissions
```

`dtuquiz:destructive_resync_quizzes` will do what you want for `--repo-delete` for quiz files on disk. (or you can just `git rm`.  If that's not enough, it's straightforward to do repo-delete as a task.

`db-delete` should be easy to implement.  I assume this should also delete any submission associated with the quiz

What others do you think we'll need?  I can imaging:

`delete-submission` to delete a submission
`ls-quizzes`, `ls-submissions` to list the quizzes and submissions
`show-repo-orphans` to list any file not reachable from a quiz (this could either be exhaustive or simple, i.e. whether it just checks that quiz files are in the right place (and also exist in the DB) and that any other file is in images, or it could go through all the quizzes and ensure that no file in the repo is inaccessible through a quiz)

others?

**Comment by dtu-compute** [comment]
Very cool!!

Yes:

* `delete-quiz` and its submissions
* `delete-submission` to delete a submission
* `ls-quizzes`, `ls-submissions` to list the quizzes and submissions

Let's wait with `show-repo-orphans` for now. Maybe something slightly different is needed after the audit.

**Comment by iainbryson** [comment]
Sounds great!

To be even more specific, I’ll add the following rake tasks:

```
dtuquiz:delete-quiz[quiz_number]
dtuquiz:delete-submission[submission_id]
dtuquiz:ls-submissions[course_id, group_id, user_id] (maybe separate tasks, i.e. ls_submissions_by_user etc..)
dtuquiz:ls-quizzes[course_id, group_id] (maybe also, by is_visible)
```

How is that?

**Comment by dtu-compute** [comment]
Perfect =)
