### ISSUE TITLE
$$ not allowed in single line text, right, wrong, hint, 

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#56]
Would it be possible to give a parsing error if `$$ xxx $$` is used in `text`, `right`, `wrong`, `hint`?

`right`, `wrong`, `hint` takes arguments, so it should also be not allowed there.

Does this belong to quiz-parser?

**Comment by iainbryson** [comment]
Both $$ and $?  Or just $$?  Yes, this would be better in the parser.

**Comment by dtu-compute** [comment]
Just the `$$` notation as it is used to put math on its own line, and that isn't possible from what he told me. He tried, and I don't think it displayed anything.

**Comment by iainbryson** [comment]
Moved to quiz-parser issue #4

https://github.com/dtu-compute/quiz-parser/issues/4
