### ISSUE TITLE
Monitor changes in courses.yaml and the yaml files it links to

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#57]
The idea was that the campus db dumper would e.g. run 3-4 times a day as a cron job, and update the users and groups for a course. New courses should also be noticed.

DTUquiz should notice any change in `courses.yml` and the files it link to. So if e.g. I create a quiz today for the class XXX, YYY, and ZZZ make it visible, and a student is added to class YYY a few days later, then the student will still be able to take the quiz even though he were not a member of class YYY when the quiz was created.

Right now it looks like the number users in a class is locked when a quiz is created.

If someone is removed from a class while logged it, the person should be able to continue like nothing have happened, but would not able able to login again.

**Comment by iainbryson** [comment]
Hi Martin,

After analyzing this for a while, here are a bunch of design considerations for your input:

1. (From the bug text): If someone is removed from a class while logged it, the person should be able to continue like nothing have happened, but would not able able to login again.
2. If a user is deleted, do we automatically remove all hand-ins associated with that user?
	* If so, things become very complicated with (1) above since we need to wait until after the logout to delete the quiz
3. If a user is deleted, do we automatically remove them from the counts for all the quizzes associated with their quizzes?
	* This will be a very costly operation and may take some time.  There may also be a need to introduce blocking into the computation of these counts which could impact other concurrent operations/quizzes
4. If a user is moved from one class to another, we need to also answer (2) and (3) in this case
5. If a user is added to a class, do we automatically add them to the counts?
6. If a user is removed from a class, can they still see their handing for that class?  Do they still appear for 'needs review'?


Big picture:

* What if we scoped the problem to allowing only additions of users, but any changes to groups?
* What if we scoped the problem to allowing changes on restart, and restart overnight?  This would avoid all the issues with having active usage while the changes are happening.

**Comment by dtu-compute** [comment]
1. My idea was that deleting a user wouldn't make any data changes, only that the CAS login would see a flag on the user and reject login. E.g. by doing a diff on the n-1 users.yml file and the current, so users.yml can remain read-only.
2. No, we shouldn't delete anything automatically. It would be great if the script in #55 also could do remove old users and their data between certain time periods. We do however have a 2017 idea, where we would like like to keep the data in an anonymous format, so it can be used to rate exercises on their difficulty level. So clean up is not high priority at this point.
3. We should keep them and don't make any changes. So clicking Visible also locks the list of students for the quiz.
4. I were just told that students in the beginning of the semester often changes class to equal out the number in each class. Would it be possible that once a student have taken a quiz (only finished quizzes) it belongs to him and he have the quiz regardless of which class he is in?
5. That would be good.
6. I am not sure I understand what "handing" means. Where they appear: What is the easiest to implement?

a. I don't think we can only add to classes, as exams can be given on different days depending on which class they are in. If we only did additions, then those that have been moved could potentially see the quiz in advance.
b. We could do that for the 2016 version, and then think about how to solve it for real in the 2017 version. Time wise it would probably be a good idea to do that

**Comment by dtu-compute** [comment]
Would it be a good idea to use Redis to cache users, groups, and courses yaml files?

**Comment by iainbryson** [comment]
In the latest schedule I break this up into the “simple file-based”
solution and a second item to perform caching and see if reds works for
that.


On Wed, May 25, 2016 at 7:26 AM, dtu-compute <notifications@github.com>
wrote:

> Would it be a good idea to use Redis to cache users, groups, and courses
> yaml files?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dtu-compute/dtu-quiz/issues/57#issuecomment-221592923>
>



-- 
— Iain
