### ISSUE TITLE
"Clone of" in meta data

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#59]
"Clone of" should be part of the meta data.

When the quiz have been created by New, it would be `Clone of none`, and if it have been cloned, it would be something like `Clone of Q1234`.

If it is a clone of a clone, it would refer to the most recent parent.

**Comment by iainbryson** [comment]
I assume this is a read-only part of the metadata.  Is that right?

**Comment by dtu-compute** [comment]
Yes, exactly.
