### ISSUE TITLE
Max Time Behavior

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#6]
I'd like to double check the logic for MaxTime.

I think the logic is: if max time is defined, it's the maximum length of time after a submission begins (i.e student agrees to the quiz launcher dialog) to when the last answer can be accepted.  Correct?

In the case of multiple attempts, is it the maximum time for ANY attempt, or for all attempts?

Can it be null, or must it always be specified?  

Here's what the spec says, for quiz reference:

Max Time is the maximum allowed time in HH:MM a quiz may take. This feature is useful if a professor wants to give a quiz over the weekend, but want to make sure that e.g. the student on have 30 minutes for the quiz.

When this time have passed the quiz website ends the quiz and makes sure that it have saved the students progress, and shows a modal to the student with the text "The quiz is over and your answers have been submitted." And the student should be redirected back to the student panel.

"Finish" overrules "Max Time". So if Finish is set to 20/1-15 13:00 and maxTime 30 minutes, and the student begins 20/-15 12:50, then the quiz ends after 10 minutes.

**Comment by dtu-compute** [comment]
> I think the logic is: if max time is defined, it's the maximum length of time after a submission begins (i.e student agrees to the quiz launcher dialog) to when the last answer can be accepted. Correct?

Yes. The students can take the quiz when they want within begin and finish dates and time, but when they start they only have `max time` to complete it.

> In the case of multiple attempts, is it the maximum time for ANY attempt, or for all attempts?

Yes, it is max time for each attempt.

> Can it be null, or must it always be specified?

Yes, null is ok.
