### ISSUE TITLE
Max time can exceed end time

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#68]
On Monday 11th at 15:00 several of the quizzes had a Max time of 8 hours and a End time at 21:00.

At this point the Max time should have been `21 -15 = 6 hours` because End time can never be exceeded.

**Comment by iainbryson** [comment]
I think I need to clarify the intended design here.

It seems first that max time and start/end time must always be consistent with each other.  Correct?

If so, we need to define how things change when individual elements get updated.

I’d guess when editing metadata that:
* if max time changes, end time is changed
* if end time _OR_ start time changes, max time changes

Does that sound correct?

**Comment by dtu-compute** [comment]
No not really. The meta data doesn't change.

In principle, the admin could set max time to 99 hours, and start and end date for 2 days, then the max time have no effect as end time comes first. This is a legit case.

The purpose of max time is, that each attempt have a max time, but end time over rules max time, if end time is sooner than max time, when the student have started the attempt.

So in this particular case, the quiz were available for 2 days with a max time of 8 hours. So when starting the attempt at 15:00, is too late, if the student wants the full 8 hours, and should therefor only be given 6 hours.

Makes sense?

**Comment by iainbryson** [comment]
OK.  So what I understand is in terms of setting max time and start/end, each is idepdenent.

The bug below however seems to indicate that when we _diaplay_ max time in the admin and student grid views, we ought to instead show an “effective” max time which is the smaller of “max time” and end_time - current_time.  Is that a reasonable interpretation?

**Comment by dtu-compute** [comment]
No, that is fine, that we display the official hard coded max time. It is the time in the nav bar when the quiz is taken that should be updated according to the current time.

**Comment by iainbryson** [comment]
So max time  will be the maximum time from the start of an _attempt_ to the end of the attempt.  But regardless, no quiz can go past the end time.

Are you sure this is still a bug then? The original text for this issue mentioned “max time” not remaining time, which is what’s in the header.

**Comment by dtu-compute** [comment]
Yes, exactly.

You are right. I meant the remaining time can't exceed end time.

I am pretty sure he showed me it, but not 100% sure. So if you can't reproduce, then close it.

**Comment by iainbryson** [comment]
I at least fixed an issue with not honoring max time in the 'remaining time'.  So I think that should resolve this.  We can reactivate if not.
