### ISSUE TITLE
Many time out messages while taking quizzes

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#74]
I suppose this is a tuning situation on when the host is down or not.

**Comment by iainbryson** [comment]
It is.  I've noticed this for a while and it's not clear why the websocket connection fails so frequently.  We could of course hide the problem by giving a longer period of time (it's now at a 1s) before declaring the connection dead.  But the effect would be also to increase the amount of risk a student will answer and the answer won't get saved.  What's the right amount of time for that delay?

**Comment by dtu-compute** [comment]
Hmm. Let's try with 2 seconds for the next update, and if it is still there, then we try with 4 seconds, and if still there, then reevaluate what to do next =)
