### ISSUE TITLE
Messages in admin panel should begin with a time stamp

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#75]

**Comment by iainbryson** [comment]
Right now, these are flash messages, intended to be short-lived and not persisted.  Do you want a solution where we keep track of these for longer and have a full timestamp?  Or simply to add the time of the message to the message.

**Comment by dtu-compute** [comment]
You raise a good point.

Do we log actions done in the admin panel, so we at some point make a "View Log" button, and the admin can read previous actions and errors?

**Comment by iainbryson** [comment]
Currently no, these are transient messages (a.k.a. flash messages) which are intended to show up and then fade away.  They don’t persist on page loads, for instance.

If you want to keep a list of these, that will have to be a more complicated enhancement.

And with the move into the admin bar, there will only ever be one visible at a time.  

So we can (1) add the timestamp or (2) make this a “full featured” log of admin actions or (3) make the messages disappear more quickly.


Which would you prefer?

**Comment by dtu-compute** [comment]
Let's go with (1).
