### ISSUE TITLE
Admin gridview headers becomes sortable without arrows

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#77]
Right now some the column headers in the admin gridview have up/down arrows for sorting.

Would it be possible to remove the up/down arrows and make each of the header cells clickable and when doing so it sorts. And when clicking again it reverse sorts.

**Comment by dtu-compute** [comment]
Reopening as the arrows are still there, and gray header background is not clickable.

**Comment by iainbryson** [comment]
Yes, I closed this one by mistake. I haven't investigated how to change this.

**Comment by dtu-compute** [comment]
If it is difficult or will produce ugly code, then we shouldn't do it. There are much more important things we would like.

**Comment by iainbryson** [comment]
Already fixed
