### ISSUE TITLE
Student number isn't part of campus dumper

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#8]
While implementing "View Submission" I noticed that the campus dumper users.yml file doesn't contain the student number described in the spec for view submission. i.e.:

ksch:
  name: Test Full Name
  email: test@dtu.dk
s654321:
  name: Test Full Name with æøåÆØÅ
  email: s654321@student.dtu.dk
s654322:
  name: Test Full Name with æøåÆØÅ
  email: s654322@student.dtu.dk
s654323:
  name: Test Full Name with æøåÆØÅ
  email: s654323@student.dtu.dk
a1:
  name: AuthØr Name1
  email: autho@student.dtu.dk

unless "654321" is the student number and "s" is a reliable prefix.

vs.:

Both have to be filled out, and the submission have to from that course. I.e. it should not be possible for a professor to guess the SID for a student, so even knowing both the correct SID and Student Number is not enough to view the students submission from another course. The student nr can be verified in the yaml file belonging to that course.

If SID or Student number is incorrect it should show a modal with the text: "SID or Student number is wrong.". and the have a button on buttom right corner which says "Close".

**Comment by dtu-compute** [comment]
I forgot to mention that part. The outer keys are the unique student/employee numbers. I.e. ksch,  s654321, ...

**Comment by dtu-compute** [comment]
Yes, the 's' is officially part of the student number.

**Comment by iainbryson** [comment]
Great!  That makes it easier.
