### ISSUE TITLE
How to tell the student that feedback will come at some point?

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#83]
Here is the situation. A student takes a quiz, where the feedback after deadline is >0, and the deadline is in e.g. 2 days from when the quiz were handed in.

If the student the day after clicks Results on that quiz, there is nothing that indicates that in one day the results will be published.

Would it be possible to generate a modal when such a quiz is viewed that informs about the feedback after deadline level for that particular quiz, and display number of days, hours, and minutes when it will happen?

**Comment by iainbryson** [comment]
How about we add a preamble to the quiz, indicating the current level of feddback shown and mentioning that more will be available on a certain date.

If the feedback before is 0, then we could hook the Results button up to a dialog as you describe.

How does that work?

**Comment by dtu-compute** [comment]
I just checked and the idea in the OP is the preferred.
