### ISSUE TITLE
Clone / update all issue

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#84]
Created Q1443 by cloning, clicked Visible, but can't be seen by the students.

When clicking "Update all" a red error message appears for less than a second. Might be related.

**Comment by iainbryson** [comment]
Martin, I just investigated this.  

It looks like the begin and end times are very very close for this quiz -- 1 hour.  Is it possible they didn't test in that window?  There may be timezone issues; the times might be in UTC.

I cloned the quiz as Q1452, added group A for my student account, changed the end time to Saturday and it did appear for me.

**Comment by dtu-compute** [comment]
I got the email 11:05 about the issue, where the quiz ends at 11:10, which is very close.

The time on the server is exactly the same as on my desktop. Both in CEST. But could it be that Ruby gets the time from another source?

Can you add the check when Visible is clicked which would say something in the lines of:

The current time have passed the quiz' end time and can therefore not be made visible.

The error on Update All. Is that related to this?

**Comment by iainbryson** [comment]
OK.  I’ll configure the server to be CEST.  It looks like it was defaulting to UTC and not local time.

Certainly I’ll add that fix to make visible.  We could go further, and prevent making visible any quiz which has a max_time which is greater than the time remaining until end_time.  What do you think?

I’m not sure about the Update All issue.  I’ve fixed the persistence issue with the messages so it shouldn’t disappear if it comes back. That fix also improves the performance of the admin page a lot.

**Comment by dtu-compute** [comment]
Thanks a lot. I'll make a note of that for future OS upgrades.

Excellent. Idea.

Great. That should be interesting to try out! =)
