### ISSUE TITLE
Make Edit Meta read-only when Visible

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#85]
#131 should be solved before this ticket because it suggests a "View state" button, which might solve this ticket.

Right now Edit Meta is disabled when Visible have been clicked.

Would it be possible to make Edit Meta read-only, when Visible?

**Comment by iainbryson** [comment]
Which of these 3 options would you prefer:

(1) A new menu option, View Meta, which, analogous to the Edit/View Quiz, would simply let one view the metadata.  Edit Meta would remain non-functional
(2) Edit Meta remains as it is, but is readonly for visible quizzes
(3) like (2) except that when a visible quiz is selected, the name "Edit Meta" becomes "View Meta"

?

**Comment by dtu-compute** [comment]
Would it be possible to make (2) and when Visible have been clicked, the quiz gets the LOCKED state from this point on, and the header of the Edit Meta modal becomes something similar to "Meta data is read-only in locked state".
