### ISSUE TITLE
Doesn't see when an error have been fixed

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#86]
Q1452 which you made, have the following error
```
vrong '$4x^3 \mathrm dx=x^4$'
```
but it didn't report this problem.

Now this quiz have been cloned to Q1453, and even when fixing this error, it is still marked as ERROR, and even shows the above syntax error in View Errors.

**Comment by iainbryson** [comment]
I think two things are going on here.

Q1452 is already visible with old version of the quiz, without the error.  So when you try to update it stops (and gives an error count, which will be a little clearer when the fix to persist them is deployed)

Q1453 not updating looks like a bug.  I've added some more logging to figure out what's going on.
