### ISSUE TITLE
For randomized multiple choice or all that apply, where should we apply the randomization?

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#9]
The random blocks are applied per submission attempt (so viewing the same submission always choses the same random question, and subsequent submissions chose different ones until they cycle).  

What about the "randomize" flag in multiple option-type questions?  Those could be randomized on every page reload, at the submission level as with Random blocks, or at the quiz level itself, once per quiz.  Another option could be to randomize per group.

**Comment by dtu-compute** [comment]
That should be once per quiz, so all students gets the same randomized order.

The feature is intended to make the professors life a bit easier, so he doesn't have to think about randomizing the options himself.

An advantage of this is also, that is it easier for the professor to compare student submissions, as he knows the order is the same for all students.
