### ISSUE TITLE
Locked state

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#91]
Depends on #90 

> There were a few issues related to this, but I do note that with the intended design, if a quiz has been or is visible, it cannot be updated.  We don’t have any visual clue for this, we just have the counts of updated vs. not.

Such quizzes could have LOCKED as their state.

**Comment by iainbryson** [comment]
Do you mean as a compile status?  Or another state (i.e. another column in the admin list?)

**Comment by iainbryson** [comment]
Ah, I just read 90. Never mind ;)
