### ISSUE TITLE
Time stamp in status message

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#97]
Would it be possible to add the time stamp after the status message? That way the admin can e.g. see when a quiz were last edited.

**Comment by iainbryson** [comment]
So the intent is to include a timestamp int he grid view, status column.  The timestamp would be the time of the most recent parse of the .quiz file if the status is OK, ERROR or LOCKED.  Is that correct?  If it’s STALE LOCKED — the file was edited — should it still be the timestamp of the most recent parse?

**Comment by dtu-compute** [comment]
1: Yes.

2: Yes, we better have the time stamp be to the current state.
