### ISSUE TITLE
Max time is empty

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#98]
2016-04-20 3df6236

When taking a quiz as a student Max time is empty in the Confirm Start modal.

**Comment by iainbryson** [comment]
Which quiz is this?  I tried this scenario locally, and it seems ok.

It’s also possible this got fixed by some of the recent changes.

**Comment by dtu-compute** [comment]
He cloned Q1461 and showed me it on the clone.

**Comment by iainbryson** [comment]
Was this was the latest deployment?  IIRC there was a bug that could have caused this before.  It shouldn’t exist still.

To look at the quiz itself I’ll need to add myself as a student and an admin in all the groups…

**Comment by dtu-compute** [comment]
I recall the build id started with `3df` and it was the one from Sunday.

Sure no problem. Add yourself to the once you want.

**Comment by iainbryson** [comment]
Now it looks like 1461.quiz is gone?

**Comment by iainbryson** [comment]
I copied the quiz file and retried the scenario, but I see max time.

It's possible this was a transient effect of some of the  code changes around max time I implemented ~2 weeks ago.  If so they shouldnt arise again.  Until it does show up again, i dont think theres anything i can do.

**Comment by dtu-compute** [comment]
Excellent.
